# Generated by Django 4.1.3 on 2022-11-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_alter_passo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntaeresposta',
            name='resposta',
            field=models.TextField(verbose_name='Resposta'),
        ),
    ]
