# Generated by Django 4.1.3 on 2022-11-14 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_alter_perguntaeresposta_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Trip Number')),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, unique=True, verbose_name='Titulo')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mapa',
            name='iamgem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mapa',
            name='trilha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.trilha'),
        ),
        migrations.AddField(
            model_name='passo',
            name='links',
            field=models.ManyToManyField(to='mapa.link'),
        ),
    ]
