# Generated by Django 4.1.3 on 2022-11-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_link_trilha_mapa_iamgem_mapa_trilha_passo_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapa',
            old_name='iamgem',
            new_name='imagem',
        ),
        migrations.AddField(
            model_name='passo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trilha',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
