# Generated by Django 4.1.3 on 2022-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0007_mapa_ordem_alter_passo_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
