# Generated by Django 4.1.3 on 2022-11-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='local',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
