# Generated by Django 4.1.3 on 2022-11-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_topico_dt_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='dt_criacao',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
